apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: test-beego
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: test-beego
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: test-beego
    spec:
      imagePullSecrets:
        - name: registry-secret
      # 定义容器，可以多个
      containers:
        - name: go-demo # 容器名字
          image: registry.cn-shenzhen.aliyuncs.com/smileai/go-demo:main # 镜像